### ISSUE TITLE
HomeKit sending power off signal even if TV is already off

### ISSUE THREAD

**Issue by Olived-fr** [nicoduj/homebridge-harmony#104]
If I have a TV (in TV Platform Mode) and I put that accessory in a scene that turns it off, it will send the power off signal even if the accessory itself is turned off prior to activating the scene.

It may have nothing to do with your plugin but I’ve been struggling with this for a while and I don’t know if this behavior is intended or not.

**Comment by nicoduj** [comment]
Hi,

thank you for feedback. It is something that is possible in "switch" mode but not yet in T mode, right. I d'ont check if a current activity is on when receiving off and it sends the off command.

Will add this to the backlog :)

**Comment by Olived-fr** [comment]
Oh great! I didn't know if the problem was on the HomeBridge side or on the HomeKit side.
Can't wait to see that feature implemented as I have often some inconsistencies between the accessory state in the Home app and the TV itself.

Merci 😉

**Comment by nicoduj** [comment]
build is on its way :) De rien :)

**Comment by nicoduj** [comment]
Done, let me know after install and config if it is ok. You should be also able to do so for inputs if you do not want the command to be sent if it is the current automation.

**Comment by Olived-fr** [comment]
Perfect it works like a charm in my case!
I’ll let you know if something doesn’t work out.

Thank you :)

**Comment by Midifreakz** [comment]
@nicoduj 

Worked for me too, but I had to remove the Tv Device from my scene, then re-add it. A bit confusing at first.

Wouldn't it be a good idea to implement the"addAllActivitiesToSkipedIfSameStateActivitiesList" parameter as a standard?  (as in: not a setting in the config file, but just there at first install) 

I can imagine that allot of people would want to add the TvDevice to a goodnight homekit scene and wil run into the same issue.

**Comment by nicoduj** [comment]
@Midifreakz strange you had to remove the device from the scene, but since we are still in beta I won’t investigate much in this .  
Concerning the default value, I asked myself the same question ;) However for switch mode lots of people thought that it was better the other way, considering that many devices have distinct codes for on/off and thus in case of any out of sync with harmony sending the command again is a good way to be sure that device are off . 

I am not so sure about tv mode , but having different behaviors for the same option doesn’t seems good either . That’s why I made the same behavior for TV mode while implementing it.

I will maybe update the default config in readme so that it is more obvious maybe ! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Midifreakz** [comment]
@nicoduj Perhaps it's an idea to make 2 different versions of your plugin after IOS 12.2 is fully rolled out?  One that works 'out of the box' for tv mode, with easy set-up(I think most people will want to use this mode because it looks super slick in homekit) and one with the switches mode, for tinkerers and use when-needed. I am pretty savvy with all of this by now and still missed this setting and it drove me mad 😂  héhé.

**Comment by nicoduj** [comment]
Hi @Midifreakz , yes I am thinking to maybe change default behaviors in 1.0.0 / dynamic platform (since I can do breaking changes in hit :) ) with a very simple configuration file indeed ! I am not really thinking of two plugins however, maintaining one takes time and there is a lot in common between the two modes . Going further in more refactoring to allow a common lib would be a possibility, but still I have a job to do also :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
