### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by Nastras** [nicoduj/homebridge-harmony#110]
Hi nicoduj,
i get the following error when switching off my Harmony Actions via the Power Off functions. Technically everything works.
Can you do something with that?

![978F6C3A-75A0-4DBC-A898-C9DA88FB7CE3](https://user-images.githubusercontent.com/27686185/54861450-2e761800-4d29-11e9-96c6-adc60b6baa2d.jpeg)
![F49AAF45-A8FE-4626-A51C-F59D07B43D56](https://user-images.githubusercontent.com/27686185/54861451-2e761800-4d29-11e9-94da-4648e62fb71d.jpeg)

**Comment by nicoduj** [comment]
ok, this a indeed only in debug mode only and with no other impact (just a log), but will be fixed thank you !

**Comment by Nastras** [comment]
I have now reproduced it in debug mode. TV turned on and then turned off.

<img width="1280" alt="Bildschirmfoto 2019-03-23 um 17 18 13" src="https://user-images.githubusercontent.com/27686185/54868756-3c12b880-4d90-11e9-8cad-564a0ae3259f.png">

**Comment by nicoduj** [comment]
Hi @Nastras , it will be fixed in 0.6.0 . You are right it appears bot only in debug mode but it si a debug log that produce this error . Still need to work on this version however in order to be sure that home controls are ok ! Hope to release it by the end of the week end . 

There is no impact , just a log I correctly understood , so no hurry in this right ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Nastras** [comment]
The error is displayed in both logs. In normal and in debug log.

As you say it does not affect the function. Everything works.

There is no hurry, just get informed of my error script via telegram if something appears with error .-)
