### ISSUE TITLE
"Buy Nicoduj a cofee"

### ISSUE THREAD

**Issue by Midifreakz** [nicoduj/homebridge-harmony#111]
Sorry for putting this in the issue section but had no other way to reach you otherwise.

@nicoduj  

I have never come across any developer on github that does such great support, has so much patience and reaches out to everybody, either noob or pro. I am really amazed by your dedication to this great plugin and therefore, I really feel like I should do something in return and perhaps "buy you a cofee". I can only speak for myself but I think you have deserved this! ;) 

If you register an account, I'll be the first to support.

https://www.buymeacoffee.com

**Comment by gitgayhub** [comment]
I’d like to buy nico some coffee but don’t have paypal account, do you accept bitcoin?

**Comment by nicoduj** [comment]
Thank you guys ! Currently I only have a paypal account but I am not doing this for money (or beer, even if like it :) ) I just want to do a great plugin that suits every one needs (or at least most of ) ! , and since I have only this repository which has a bit of « success » it is quite reasonable to give users the support they deserve !  But thanks again for those messages, it conforts me in putting some time and energy in this repo :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by durosity** [comment]
Sure you don’t want a little donation?  Even to your favourite charity?

**Comment by nicoduj** [comment]
I have finally added a little paypal button on the readme :)

**Comment by nicoduj** [comment]
closing this one since I finally add my paypal account on readme page :)
