### ISSUE TITLE
[BUG] Home Control buttons  : all home devices are exposed

### ISSUE THREAD

**Issue by mikesalz** [nicoduj/homebridge-harmony#118]
First - THANK YOU for adding the Home Control buttons!  I know that was a lot of work, and I really appreciate it!  I tried it this morning, and ran into an interesting bug.  When I enabled it (code below), all of my Lutron Caseta and Philips Hue accessories showed up as additional Homebridge accessories.  They still exist as native HomeKit accessories as they are supposed to, but are now duplicated through Homebridge.

```
  {
    "platform": "HarmonyHubWebSocket",
    "name": "FamilyRoomHarmonyHub",
    "hubIP": "192.168.1.228",
    "showTurnOffActivity" : false,
    "publishHomeControlButtons" : true
  },
```

![image](https://user-images.githubusercontent.com/46855061/54996361-7900ca00-4f9f-11e9-9636-f6b1859a9f17.png)

**Comment by nicoduj** [comment]
Hi, what would you expect those to do ? I think they are useless if your devices are already HomeKit no ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikesalz** [comment]
Well, I wouldn't expect them to be there at all.  I would only expect the four Home Control buttons to show up when I add publishHomeControlButton.  But instead of the Home Control buttons, I am getting the duplicated Caseta and Hue devices.

**Comment by nicoduj** [comment]
Caseta are your hue devices right ? They were there before ? The purpose of this option is to be able to add a switch for the corresponding action on your physical harmony. Some users are using this with emulated hue devices (or other home device) that are not HomeKit compatible . This way they can add them also to HomeKit. If you have those buttons linked to hue lights, then don’t use this option at all :) ! It will be redundant 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikesalz** [comment]
OK, maybe I misunderstood.  I thought what you were doing was exposing the actual Home Control buttons to HomeKit.  But rather, you are exposing the devices that the Home Control buttons are controlling?

**Comment by nicoduj** [comment]
Hum... i don’t have one my self so I might have done something wrong :) could you tell me what actions are triggered by your home controls button on the physical remote ? Launching in debug mode and giving me your home config would be nice also !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikesalz** [comment]
I have attached the log.  I have three Harmony Hubs.  The family room one is where I enabled publishHomeControlButton.  The buttons SHOULD be controlling these:
1. hue-light.harmony_movie_night (Emulated Hue)
2. hue-light.harmony_movie_end (Emulated Hue)
3. Lutron Caseta Kitchen Lights (Native HomeKit device)
3. Lutron Caseta Kitchen Table Lights (Native HomeKit device)


[Log.txt](https://github.com/nicoduj/homebridge-harmony/files/3008646/Log.txt)

**Comment by nicoduj** [comment]
Thank you will give it a look, indeed from what I see I currently publish everything !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dlindberg** [comment]
I was experimenting with this some last night and ended up reading through #67 a couple of times to wrap my head around this one. It does seem to just publish everything that the HarmonyHub knows about, so if you have real devices on real hubs connected to HarmonyHub those would be duplicated if HomeKit also already understands them.

My work around to use the Harmony Remote's home automation buttons prior to this release was to have fake devices (using the SmartThings in built Virtual Device Creator) on a real SmartThings hub controlled by the Harmony home control buttons. Publish those to HomeKit via the SmartThings home bridge plugin and then have HomeKit actions watch those devices.

When I add `"publishHomeControlButtons" : true` all those fake devices show up a second time. I should test what happens if I disable the plugin and or disable the SmartThings hub, I'll try and do that when I get home.

I'm not certain what the *best* behavior pattern for this is. But I would lean towards [BetoRn's comment](https://github.com/nicoduj/homebridge-harmony/issues/67#issuecomment-467505021) being on the right track. Having all four home control buttons published back to HomeKit as a single momentary switch device with four buttons each with a short press and long press function. Then in HomeKit it would be possible to set the actions those buttons carry out directly from HomeKit and without setting up actions that watch for events on devices. This works well if you are HomeKit centric but have a few devices you need compatibility for. I don't know how it would suit other use cases.

I think the documentation for such a design can be a bit more straightforward. Basically create four fake devices that Harmony is compatible with and remove all other automation devices from Harmony, link them to your four automation buttons and turn the feature on in the plugin on and you get a momentary button exposed that lets you control things based on your interaction with those buttons. Some instructions for making those fake buttons would probably be good, but my method seems less than ideal for that. That works in a HomeKit centric workflow, but might not be the best solution if someone is trying to have HomeKit as a smaller part of a more complex home automation setup.

**Comment by nicoduj** [comment]
@dlindberg to be honest I am not sure anymore of the use case for those home automation exposed from harmony.

First, I realized today that there might be no way to map the physical buttons themselves. They send IR command to the hub that maps them to a home device action. The harmony app doesn’t handle those commands , it handles the home device themselves. Thus, there is no information through api for the buttons.

Considering that, i get only all home device exposed through harmony hub, and currently publish them all which is bad, because some like hue are allready in homekit ( even fake hue bulb) .

So I am wondering if there is any smarthome device that harmony can expose / handle and that are NOT homekit compatible : it would then make sense for them, and I would have to give an option to configure which one should be exposed.

But currently’ it makes no sense, and this is definitely not exposing the physical buttons

**Comment by dlindberg** [comment]
As excited as I was to see this feature in the change log, I think you might be right. Those automation buttons on the remote are really hamstrung by how Logitech has chosen to implement them. Even if you have compatible devices any scenes you might want must be created in the Harmony app as a one off, it doesn’t understand scenes created in Hue, SmartThings or Lutron; I don’t know for sure about the few other things it supports, but my expectation is that it does not work. So they kind of suggest usefulness but are a pain to use in a meaningful way.

On the testing front disabling the SmartThings HomeKit plugin and then disconnecting the SmartThings Hub from the network and power, the buttons still work with your implementation, so literally nothing needs to actually exist so long as you have some way of tricking your Logitech remote into thinking it is talking to something in the first place. The bright side of that is the HomeBridge SmartThings plugin is a real bear to setup and that was literally the only thing I was using it for at the moment.

Ultimately the challenge I kind of see is that there is a bit of a barrier to setting the Harmony to think it is talking to a fake automation device. Even if you take into account people that have already successfully setup HomeBridge. Setting up those fake devices seems like it is well beyond the expected scope of this project though. However, for the feature to be helpful broadly, being able to point to a docket-compose file that you can just spin up next to HomeBridge on a Raspberry pi and point the remote to might be enough to get the setup done. Much nicer would be Logitech just letting me link the darn thing to my Logitech Pop hub and treat them all like POP buttons… I honestly don’t know why they don’t just do that…

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
@dlindberg thank you for testing . If I understand, you setup scenes in harmony app that use a lot of home device and can trigger them once associated to the button on the remote (or a Logitech pop button). Are Logitech pop button visible in your setup as home accessories ? Since they are not HomeKit compatible it could be a way to overcome this , but not sure since I think they are more triggers than receivers ... 

The more I think about it the more  I think I have to move this option to a list of home devices  users would like to add as switches, in case of compatibility only with harmony and not with HomeKit, but not so usefull and don’t even even know if there are some !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dlindberg** [comment]
Re-reading my comment I think I got a bit off topic venting some frustrations with how Logitech treats the home automation buttons on the remote, so it got a bit confused.

To me, Logitech's intended workflow is really horrible and feels intentionally hamstrung by Logitech. I'm reticent to make strong statements of what should happen though—because, how I think this should be implemented contradicts their default configuration, so could be problematic for anyone that has tried to follow Logetech's intended path.

## How I currently have things configured:

* Create 4 fake devices on my SmartThings hub (one for each automation button). (SmartThings is one of a couple devices that is not compatible with HomeKit but is with the Harmony Hub, and they have a very easy to use fake device maker.)
* Expose those fake devices to the HomeKit app. (Previous to your update I had been using the SmartThings homebridge plugin to accomplish that, the ^0.6.0 update has the benefit of the SmartThings Hub not needing to exist past the convincing the Harmony Hub it is doing something phase, so I do consider that a small victory)
* Use the HomeKit automations section to create triggers that watch those fake devices. When they change state I have it trigger a HomeKit scene. I could also do the same thing for when specific activities are started, but I've found that to be less useful in practice, though it does sound good at first.

## How Logitech wants you to do this:

* Tell your remote about all the compatible devices that you have on your network.
* For each button (and on activity triggers if you wish) add one or more of these physical devices.
* Set what you want all those devices to do when triggered (Depending on what the devices are you can turn them on or off and adjust color and dimming level).
* Do that for every button and activity. You cannot re-use anything that you've done for another button or activity and you have no access to any scenes you may have created on a compatible hub or device.


## Pop Buttons

I mentioned the Logitech POP Smart Buttons simply because they are implemented a lot more like my desired implementation then they are like the Logitech remote's buttons. They are  directly HomeKit compatible (You can use a POP button either with HomeKit directly or with Logitech's (not very good) POP app. You can't use them both ways at the same time though and the instructions for that part are supper confusing on their website; once you get past that they actually work great with HomeKit assuming you have the HomeKit compatible POP Bridge, I think the first generation bridge was not HomeKit compatible), so it is a bit frustrating that it feels like Logitech *could* give me what I want, but that they just don't... What's really crazy is the POP Bridge totally knows about the Harmony hub and will quite happily trigger an activity on that for you. The the problem is using the POP Bridge as a receiver for the Harmony Remote's automation buttons is something I think Logitech would need to implement, and I see no sign that they might do that.


## What to do?

I'm not really sure. Your current implementation works well if you are already faking out the Harmony Hub to get it to be more useful, but duplicates a lot of stuff if you set it up the way Logitech want's you to.

If you were to continue down the path of give the remote fake devices to control and then make them do something useful elsewhere I think exposing all four buttons together as a momentary trigger device in HomeKit makes a lot of sense (one device with four buttons each with two events that can happen, short press and long press), that is quicker and more straightforward for setting up scene or device triggers then setting them up in the automations section and would have a bit less clutter in the home app.

If most people it to follow real physical devices so that your Harmony Hub is bridging to non-compatible devices them my suggested implementation would work quite badly, horribly really. My feeling is that compatibility layer is better done directly in Homebridge through the requisite plugins. I don't think anything that the Harmony Hub is compatible with isn't compatible with HomeKit either directly or through Homebridge so I'm not sure there is any major win to be lost on that front. But I don't feel comfortable saying that as categorically so or the best choice.

The challenge is my use case has the pre-request of have some way to make the Harmony Hub think it is talking to devices for it to work at all, so some way to create compatible fake devices. That isn't the most straightforward thing to do, especially if you don't have a stray SmartThings hub lying around and need to virtualize the whole thing.

I do think there is something here, I think it just depends on which use-case the implementation targets what the path forward is.

**Comment by nicoduj** [comment]
I have added an option to select the one you want to expose for now. This way you can expose only the one that are not already HomeKit compatible .

**Comment by GMarty93** [comment]
Hi how does this feature work now? I haven it turned on but my the hue devices I have set under the home control buttons don’t appear in homekit. Do I have to specify the Home Controls To Publish As Accessories Switch? If so what info does it need?
