### ISSUE TITLE
Set category to tv for pairing external device

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#119]
See @KhaosT comment on twitter ;)

Plus remove non existing 0.0.48 homebridge ref :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KhaosT** [comment]
I'd suggest you always publish TV accessories as external accessories, instead of having one in bridged mode while the rest as standalone, since there is no guarantee that user don't have any other plugins that published TV service in this way.

https://github.com/nicoduj/homebridge-harmony/commit/897b190d77d33577f60d806ec89f12d7d7db8ff0#diff-55376acb9c67c5556243b9296540fd35R220

**Comment by nicoduj** [comment]
>I'd suggest you always publish TV accessories as external accessories, instead of having one in bridged mode while the rest as standalone, since there is no guarantee that user don't have any other plugins that published TV service in this way. ...

@KhaosT your damn right thank you for suggestion . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
@KhaosT : you were right, so much more beautiful with the category set :)

![IMG_3272ED102F1F-1](https://user-images.githubusercontent.com/19813688/55102807-84e7ab80-50c7-11e9-9214-d3231f7f73e2.jpeg)
