### ISSUE TITLE
TV remote from control centre sometimes work sometime doesn't

### ISSUE THREAD

**Issue by maisun** [nicoduj/homebridge-harmony#121]
Hi,

Thanks for the great plugin, the TV mode is really well thought and works great great in Home app. I got some strange issue with TV remote in control centre though, sometimes I can see the remote and use it without problem. Other times I don't even see the remote. 
No sure if it has some conflict with other TV remote plugins. I can only see one of them - either Harmony remote or the other remote. Does the remote get registered during startup of HomeBridge? Is there any limitation on how many remotes one HomeBridge instance support?
Thank you in advance!

**Comment by nicoduj** [comment]
Hi,

As described in #54, it is an issue with homebridge / homekit. In currently beta 1.0.0 f my plugin, and latest version oh Homebridge, it is possible to have multiple hubs, but all other plugins you are using should adopt the "external accessory" way. I am continuing my work on this, because current beta might stil have problems since I made a bad choice by not adding the first TV device of my plugin as an external accessory.
