### ISSUE TITLE
[FEATURE] Custom name 

### ISSUE THREAD

**Issue by overflywingo** [nicoduj/homebridge-harmony#122]
Hello

For "devicesToPublishAsAccessoriesSwitch" , is it possible to put in the Config.json our own accessory name ?  I mean the one that will be displayed on the Home app switch ? 

For instance,  "devicesToPublishAsAccessoriesSwitch": [
                "TV Samsung;Play", ... in config file 

is currently displayed as TV Samsung-Play in the app, but I would like to get something else. 

I know I can rename it in Home App, but I would like to have that custom name defined directly in the config.json file 

Thanks

**Comment by nicoduj** [comment]
Hi, this name is generated for unicity purpose, and composed of the name of the device in harmony and the name of the command if you add one. I could definitely add  an option to define their name but I think it becomes too much complicated in terme of configuration since you can in fact rename them in HomeKit . With 1.0 and cached accessories the risk of loosing custom names is also lower, so I am not sure to consider this .

I will think of it however / will wait if other users want that or not, so keeping this open for the moment  :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by overflywingo** [comment]
Thanks for the response Nicolas.  In fact the idea behind this suggestion is to be able to use "non-standard" letters & signs in the name. 
For instance if you try to rename via the Home App, many 

Just have a look of what I did using the "Broadlink RM"  which allows renaming in config.json .. and therofore the use of non-standard signs like EMOJI's. 
But this is not not possible with renaming in Home App, because the use EMOJI's (and other special signs) is prohibited

**Comment by nicoduj** [comment]
@overflywingo good point and yes I saw that. However the name in home app is what they call the Siri name, how could your device respond to Siri with such names ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by overflywingo** [comment]
Joker ;)  .... But I'm learning EMOJI langage intensively .. It's hard but I 'll be ready to pronounce it before very soon

**Comment by nicoduj** [comment]
Will think of it, if anyone else vote for this :)
