### ISSUE TITLE
Harmony control of HomeKit scenes?

### ISSUE THREAD

**Issue by Vortec4800** [nicoduj/homebridge-harmony#18]
I'm looking for a way to trigger HomeKit scenes from buttons on my Harmony. It looks like this plugin is designed in the opposite direction, triggering Harmony activities from HomeKit.

Is what I'm looking for possible?

**Comment by nicoduj** [comment]
Hi,

Indeed the plugin for homebridge does this opposite. I don’t know if any solution to do what you want, since there is no « trigger » that can be set with harmony. You can upvote this feature that would allow to do such things but I doubt Logitech will open his system ... https://community.logitech.com/s/question/0D53100006u0CzxCAE/feature-request-harmony-to-call-arbitrary-urls . There is some workaround suggested there also but didn’t try them myself

**Comment by JangoBritt** [comment]
Although, you could use this to mount "virtual devices" into Homebridge, and then use those to control HomeKit scenes through automation...

create a Device using an old unused remote (like a Xmas light one), and present that to HomeBridge. When your Harmony Remote sends that on/off command, it should register in HomeBridge, right? and then use that device as the trigger for your scene
