### ISSUE TITLE
[BUG] Second hub

### ISSUE THREAD

**Issue by raphaeldavid** [nicoduj/homebridge-harmony#199]
**Describe the bug**
Since the Homebridge docker update, I only see one of my hubs

**To Reproduce**
Add 2 hubs to your config

**Expected behavior**

**Screenshots**
![Capture d’écran, le 2019-10-21 à 21 07 14](https://user-images.githubusercontent.com/10728443/67253658-e21dc280-f446-11e9-9b81-df9140b30761.jpg)

**IOS (please complete the following information):**
- Version [e.g. 13.2]
- Device: [e.g. iPhone11ProMax]

**Logs**
Your log in debug mode (-D option)

**Config**
        {
            "platform": "HarmonyHubWebSocket",
            "name": "HarmonyHub-RDC",
            "hubIP": "192.168.1.43",
            "otherPlatforms": [
                {
                    "name": "HarmonyHub-SS",
                    "hubIP": "192.168.1.44"
                }
            ]
        },

**Additional context**
Everything worked before the docker was updated

**Comment by nicoduj** [comment]
Hi, is your second hub still discovered by the plugin ? (Check logs). 
If yes you can try first to reboot your phone / HomeKit hub . 

If this does not work, and since I think the hub missing is the one that was added manually as an external device, try removing it in home app, and add it again . 

I really don’t know what happened, external device relies on bonjour protocol so maybe the update of your docker changed something in the network level that changed the discovery of the hub.

Which docker config / version are you using (on Synology ?). What are you network settings on docker ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by raphaeldavid** [comment]
Thank's for your quick answer.

I erased it and put it back and it works now.

Thank,
