### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by schweppy** [nicoduj/homebridge-harmony#214]
Hi
I was using this plugin fine until my router failed and since replacing it, the harmony hub is now on a new IP address. HomeKit is now showing 2 instances of the hub, the old IP and the new one. I have tried turning on “clean cache” and also have tried removing cachedAccessories directly from my Pi4 but the old hub is still showing in HomeKit. 

The second issue is that every time i restart homebridge, the harmony hub resets back to “Default Room” in home app.

Any ideas?

**Comment by nicoduj** [comment]
Hi, why didn’t you assigned the same fixed up through your new router ? Has mentioned you must have a static ip set for your harmony hub.
If it resets to default room, it is probably because it is seen as a new device each time. If you played with clean cache and cached accessories / persist folder, be sure to turn the option back off, and clean also files for harmony at your homebridge root directory . I would need your config file and logs in debug if you need more help 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schweppy** [comment]
I didn’t realise it needed to be static. Have now changed it back to old IP but it is still showing the original duplicate instance in HomeKit.
The option is definitely off for cleancache??
Configure file looks like this - 

"platform": "HarmonyHubWebSocket",
"name": "Living Room TV",
"hubIP": "192.168.0.5",
"cleanCache": false,
 "mainActivity": "Apple TV",
"playPauseBehavior": false

**Comment by schweppy** [comment]
The only real error in the log i can see is this - [Living Room TV] WARNING - configureAccessory - The platform HubName is not there anymore in your config (name property). It won't be loaded and will be removed from cache.

**Comment by schweppy** [comment]
Have now removed persist folder and completely removed homebridge from HomeKit but when readding the old TV with remote is still there???? I’ve turned off TV accessory in harmony config as well so only showing the one old accessory????

**Comment by nicoduj** [comment]
You have probably added it once as external accessory just delete it in home app on ios

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schweppy** [comment]
Started from scratch and all working as it should be. 

The control centre remote doesn’t work on my Apple TV. Any ideas? iPhone Volume buttons work fine for my AV Receiver.

**Comment by nicoduj** [comment]
I don’t really understand what you mean , the control center remote bonds it’s command to the one of the current activity (volume, arrows...)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schweppy** [comment]
Yes and all activities the remote works ok except for the Apple TV activities. This does not control the Apple TV like the harmony remote does.

**Comment by nicoduj** [comment]
You will have to check the logs in debug mode to verify what key binding is in place with this activity . You can always override them in config if needed (see readme)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MikeDeltaHH** [comment]
@schweppy 
Do you use hoobs or the native homebridge? I switch from homebridge to hoobs in the past and have the same problem that the hub was reset to the default room when i´m restart hoobs - switch this plugin back to my old homebridge installation and this doesn´t occurs again so i think this problem is hoobs related...

**Comment by nicoduj** [comment]
I have improved options handling in 1.2.4, so that cleanCahce option set to "false" and not false is not interpreted as true.

Let me know if it is ok .

See #219

**Comment by nicoduj** [comment]
I am closing this since I had no feedback, feel free to re open if necessary 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
