### ISSUE TITLE
TV and switches remain after removed and plugin uninstalled

### ISSUE THREAD

**Issue by rixmix123** [nicoduj/homebridge-harmony#226]
I know there have been a few issues request put out there about the TV switches and manual switches showing up with multiple hubs and remaining after removal. I tried to look through the old issues and could not find an exact fix for this. Can you please provide?

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**IOS (please complete the following information):**

**Logs**
Your log in debug mode (-D option)

**Config**
Your config section of platform. Please do not post your whole config and especially with logins / passwords !

**Additional context**

**Comment by nicoduj** [comment]
Hi, can you check the log at homebridge startup to be sure that everything is uninstalled ?
If you had external tv accessory, you must remove them through home app.
Finally, please be sure to restart all your home connected device (iPhone/ iPad/ Apple TV ...) since sometimes iCloud sync is messing things up . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Hi, is it ok now ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rixmix123** [comment]
I just ended up deleting homebridge and reinstalling. I will close the issue.

**Comment by rixmix123** [comment]
Thank you!
