### ISSUE TITLE
Room Assignments Not Being Saved 

### ISSUE THREAD

**Issue by GRClark** [nicoduj/homebridge-harmony#227]
Every time I reboot HOOBS server the room assignments are being reset back to “default room”.

**Comment by nicoduj** [comment]
Hi, Is it the same issu I replied on Reddit ? Probably because cleancache has been set to true.

https://www.reddit.com/r/homebridge/comments/f7ho4e/harmony_room_assigment/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Or

https://www.reddit.com/r/homebridge/comments/f73lz9/harmonyhub_plugin_resetting_room_assignments/?utm_source=share&utm_medium=ios_app&utm_name=iossmf


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
