### ISSUE TITLE
Feature Request: Dynamic Discovery of Hubs

### ISSUE THREAD

**Issue by donavanbecker** [nicoduj/homebridge-harmony#238]
It would be nice if this plugin would discover hubs that are on the local network and add to Homebridge. This would clean up the need for the other hub option on the config.schema.json and an blacklist option could be added to ignore hubs that are not wanted in HomeKit.

**Comment by donavanbecker** [comment]
Maybe this will help?
[harmonyhubjs-discover](https://github.com/swissmanu/harmonyhubjs-discover)

**Comment by nicoduj** [comment]
Will take a look, thx ! Concerning the "other hub section", I don't really understand what you mean, since even if autodiscovery is enabled, I think users should still be able to distinguish options between hubs (activities to expose or not, and so on). But definitely, it would be needed only for advanced users, and the config could be "empty" for default behaviors and even for multiple hubs.

**Comment by donavanbecker** [comment]
[harmony-api](https://github.com/JordanMartin/harmonyhub-api) and [pyharmony-ws](https://github.com/NickWaterton/pyharmony-ws)

**Comment by donavanbecker** [comment]
> Will take a look, thx ! Concerning the "other hub section", I don't really understand what you mean, since even if autodiscovery is enabled, I think users should still be able to distinguish options between hubs (activities to expose or not, and so on). But definitely, it would be needed only for advanced users, and the config could be "empty" for default behaviors and even for multiple hubs.

I think I might have not understand how powerful that section is, forget that part of what I said ha.
