### ISSUE TITLE
[FEATURE] Eve App 4.2 Issue with homebridge-harmony devices

### ISSUE THREAD

**Issue by DJay-X** [nicoduj/homebridge-harmony#249]
@nicoduj 
The lates Eve for HomeKit App v4.2 is causing issues with several Homebridge Plugins.
They changed something so that the serial number of a device is linked somehow in the background. This was not the previous Eve version.
Problems causing now like described here.
https://github.com/homebridge/homebridge/issues/2503

So alle devices/switches from homebridge-harmony can't be sorted anymore and can't get an icon for each device separately. 

Do you see a solution to fix this "Eve" Issue, by changing something in your plugin?

Thanks again for your work and the time you are investing generally.

**Comment by nicoduj** [comment]
Hi, I can make serialnumbers "unique" I think, but it won't help in case of multiple service son the same accessory (since serialnumber is on accessory) . Did you try playing with *AsIndividualAccessories options in roder to see if switches are multiples services of one accessory, the problem persists ?

**Comment by nicoduj** [comment]
----
EDIT

Let's try 1.3.5 that will be out soon. It should change the serial numbers to be unique after reboot (you will see warning logs), I think there is no need to clean cache (hope so) from my tests. I have also change something to be compatible with next 1.0 version of homebridge, hopping it won't mess up the cache also (did not on my setup)

------


if you are ok doing some test on your setup, you can try to change line 1188 of harmonyBase.js to this :

```javascript
myHarmonyAccessory.serialNumber = uuid;
```

instead of this : 

```javascript
myHarmonyAccessory.serialNumber = harmonyPlatform.hubRemoteId == undefined
        ? harmonyPlatform.hubIP
        : harmonyPlatform.name + '-' + harmonyPlatform.hubRemoteId;
```

You will need to clean your cache I fear (and thus loose all your devices)

**Comment by DJay-X** [comment]
First of all thanks for your fast action. 🙏

I updated to 1.3.6 restarted homebridge but the serial number on my 3 harmony devices and the PowerOff button is still all the same. The IP number.

I deleted "cachedAccessories", and `sudo npm cache clean -f` rebooted the Pi but still the IP without any difference or extension on all devices.

>  I think there is no need to clean cache

How/where do I have to clean cache the way you are thinking.

**Comment by nicoduj** [comment]
Check in home app please it seems eve does not update it...

**Comment by DJay-X** [comment]
Correct. Home App is now showing the unique serial numbers for every harmony device.
Eve App is still not changing anything. 

Only after deleting Eve App completely and reinstalling it, it now is showing the unique serial numbers as well.
By this, also sorting the devices separately and give each one individual icons is working again. 👍 

YOU fixed the Eve App. ;)   

Maybe your work with this is a great example for other developers. You should somehow mark this as a solution. 
Unfortunately not every developer is still maintaining their plugins. Some Plugins still work well after several years without an update. But there is zero chance they change the plugin like you did. 

In my setup at least the first plugin problem with Eve is fixt. 
And I thank you so much for this. 

The rest is probably to do by Eve Developers in general with a next Eve App update.
