### ISSUE TITLE
Other TVs

### ISSUE THREAD

**Issue by roberkane212** [nicoduj/homebridge-harmony#299]
I’m not sure what I am doing wrong, but I can’t get any more then one tv to come up in HomeKit. The main tv I put into the config file. I have publishalltvs ect however none of my other TVs show up here is my config 

"name": "28\" Sanyo TV",
            "hubIP": "192.168.1.54",
            "hubName": "Harmony hub",
            "cleanCache": true,
            "publishAllTVAsExternalAccessory": true,
            "activitiesToPublishAsInputForTVMode": [
                "DVD",
                "Watch a Movie",
                "Watch Fire TV"
            ],
            "TVAccessory": true,
            "mainActivity": " The TV",
            "platform": "HarmonyHubWebSocket"

**Comment by henf** [comment]
What is your name of your harmony hub? Have you tried to exchange the "name" of your TV to the name of your hub? 

E.g. in the first line my json is:

"name": "Hub WZ"
"hubIP": ...
Etc-

Whereas "Hub WZ" is the exact name of my hub I gave it in my harmony app.

Hope that helps

**Comment by nicoduj** [comment]
Hi, not sureI understand your issue, but some things first about your config :

Name is not good since there is a «  in the name
You have to choose between hubip and hubname (use ip only if your hub has got a fixed one by your network)
Cleancache must be removed / set to false (only use if you have trouble with cached accessories but won’t have any effect on tv accessory especially if you publish them all as external)

When you are talking about multiple tv ... do you have multiple hubs ? It is the hub that is published as a tv accessory with its activities , not devices ...

**Comment by roberkane212** [comment]
@nicoduj no I have  TV’s through another plugin. These TVs are also added to my harmony hub. I read that others TVs would be exposed by harmony as separate accessory. I was just wondering how this is possible as I have tried to add them, but not working for me

**Comment by nicoduj** [comment]
My plugin only expose activities as a tv accessory with multiple inputs , not devices (devices can be added as switches manually)

**Comment by roberkane212** [comment]
@nicoduj so what I need to do is add the other tv’s in activities in harmony to be able to expose them in HomeKit?

**Comment by nicoduj** [comment]
Hi,
I am not quite sure tounderstand your setup, but If you have multiple TVs handled by one harmony hub / remote, You indeed have to setup an activity for each TV so that remote switch from one to another (and you can decide what "switch off" behavior you want on the harmony side - pleas erefer to their documentation).
