### ISSUE TITLE
Devices view in the eve app

### ISSUE THREAD

**Issue by Nastras** [nicoduj/homebridge-harmony#301]
Hello @nicoduj,

I have displayed my Harmony Hub as a device in the Home app. When I select the device, my Harmony Actions are displayed as subordinate buttons.

When I use the Eve app, the Harmony Hub is not shown as a device but the Actions are shown one by one.

So I wanted to ask you if you have an idea how I can show my Harmony Hub as a device in the Eve app?

Here is my config:
{
"platform": "HarmonyHubWebSocket",
"name": "Fernseher Wohnzimmer",
"hubIP": "192.168.XXX.XX",
"showCommandsAtStartup" : "false",
"showTurnOffActivity": "false",
"TVAccessory" : "false",
"switchAccessories" : "true",      
"publishSwitchActivitiesAsIndividualAccessories": "false",
"addAllActivitiesToSkippedIfSameStateActivitiesList": "true",
"mainActivity" : "TV",
"devicesToPublishAsAccessoriesSwitch": [
],

![IMG_0002](https://user-images.githubusercontent.com/27686185/94146736-abc99e00-fe74-11ea-99cd-ecabb9a9748f.jpg)
![IMG_0005](https://user-images.githubusercontent.com/27686185/94146753-af5d2500-fe74-11ea-81cc-4b3b3d8c1eeb.jpg)
![IMG_0006](https://user-images.githubusercontent.com/27686185/94146754-aff5bb80-fe74-11ea-9eb8-23329bc99975.jpg)

Thanks a lot!

**Comment by Nastras** [comment]
Note:

When I select one of the Actions in the eve app, the Harmony Hub is displayed correctly as TV Living Room with all Actions as subordinated switches.

![IMG_5B11DF3D92AD-1](https://user-images.githubusercontent.com/27686185/94147074-1975ca00-fe75-11ea-86b6-ddb3965fb3be.jpeg)

**Comment by nicoduj** [comment]
Hi,
Home app can split or group services of an accessory. By default it groups them, so that is why you have this result since you are not publishing your switches as individual accessories.

I have no control on how the eve app is working, It seems that it shows each services separately (except in accessoreis section in settings which seems logic),and not grouped by accessories (which is not the case Please also note that eve won't show any TV accessory.

So I can't do anything about this, sorry !
