### ISSUE TITLE
[BUG] when adding an activity in harmony app, external accessory needs to be removed / added again

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#316]
**Describe the bug**
when adding an activity in harmony app, external accessory needs to be removed / added again
otherwise, new activity will be seen outside of inputs, as a service.

**To Reproduce**
Add an activity in harmony ap and restart homebridge

**Expected behavior**
should be added to input list without need to remove

**IOS (please complete the following information):**
- Version 14.1

**Comment by maisun** [comment]
I experienced this issue twice in the past but most recently I added an activity "Game" and it works out of box with a restart.

**Comment by nicoduj** [comment]
Can I ask which version you were on (iOS / plugin) and if you are set as an external accessory or not ?

**Comment by maisun** [comment]
Hi, please see the info below:
1) iOS: version 14.0.1
2) Plugin: version 1.4.0
3) Yes external always (I have another plugin only supports internal)

As I wrote I have seen this issue twice in the past (I think before I upgraded to iOS 14 but not sure if it's due to that), a few days ago when I added "Game" activity I was surprised it worked out of box by just restarting HB.

**Comment by nicoduj** [comment]
Thx.
What version of hb are you on please ?

**Comment by maisun** [comment]
> Thx.
> What version of hb are you on please ?

It is version 1.2.3.

**Comment by nicoduj** [comment]
to be tested in version > 1.1.6

**Comment by nicoduj** [comment]
Can't reproduce, closing
