### ISSUE TITLE
[FEATURE] custom set characteristics in config file

### ISSUE THREAD

**Issue by carlosgamezvillegas** [nicoduj/homebridge-harmony#319]
Hello guys, thank you so much for this plug in, I love it having it in my Home. 

I have one request regarding the characteristics set on the plug-in. Could you add “Model”, “Manufacturer” and “Serial Number”  to the settings so we can change them manually? Right now when you try to see the details of the vacuum in HomeKit it says “harmony” for model and a long serial number. I have tried to change the .setCharacteristics on the js but it doesn’t seem to work. I have done that with other plugins but I can’t make this one work. I think this will help to make it look more like a native HomeKit device .

Thanks,

**Comment by nicoduj** [comment]
Hi, could you explain why it would be important ? Currently version is the plugin version, modèle is the name set in your config, and serial is auto generated so that it is unique for each device (since many can be published).

I think such option would confuse and can't see why it would be important ?

**Comment by carlosgamezvillegas** [comment]
Hello Nicoduj,

Thank you so much for taking the time to answer. I think having this option adds an extra level of polish to the plug-in. As you know, it does not affect the way it runs, it is more for aesthetic purposes. See the image below, I was finally able to do implement the change, for some reason I had to reinstall the plug-in to apply the changes. I modified the config.schema and the HarmonyBase.

Best,
![IMG_1038](https://user-images.githubusercontent.com/67111609/100810666-ca589200-33ed-11eb-945c-da1740d5dc43.PNG)

**Comment by nicoduj** [comment]
Hi,

As I said I won't do that since the plugin can publish many accessories, and this would need to be able to put a name in the config for each one (which would be painful).
Model is already done through config. I will change Harmony to logitech, since it is indeed better. Serial number will remain auto generated since it must be different for each accessory to avoid issues with other apps like Eve, which happened in the past.

**Comment by carlosgamezvillegas** [comment]
Hello,

Actually, the process is not painful since it only changes the AccessoryInformation and not the unique ID for the accessory.
These are the only lines I had to change to make it work  in the createAccessory section:

    let myHarmonyAccessory = new Accessory(fullName, uuid);
    myHarmonyAccessory.name = fullName;
    myHarmonyAccessory.model = platform.model || 'Harmony Hub';
    myHarmonyAccessory.manufacturer = platform.manufacturer||'Logitech';
    myHarmonyAccessory.serialNumber = platform.SerialNumber||'1651WD080308';

And it does not create any issues with EVE. I have tested it.

**Comment by nicoduj** [comment]
Hi,

createAccessory is called for each accessory, so it will result with all accessories to have the same serial number (which **in the past** resulted in some trouble in eve - fixed now indeed but not sure it won't come back since for a single platform, it is not really "epected" to have same serial number for all accessories. 

Model is allready reflected through the config, where you can put whatever you want.
Manufacturer will be Logitech as I said in a next release .

As a result, I d'ont think new config key is necessary :)
