### ISSUE TITLE
[FEATURE] Other device types?

### ISSUE THREAD

**Issue by sleepyarmistice** [nicoduj/homebridge-harmony#358]
First, thanks for this great plug-in. Easily one of the best! One thing I’ve noticed lately that would be nice is to be able to have the hub advertise itself to HomeKit as a device other than a tv, like a receiver or a set top box. Right now, my hub is only controlling a receiver set up as a stereo and I have it configured to reveal the activities as switches. I would like to be able to just have them represented as one device and to have volume control.

**Comment by nicoduj** [comment]
Hi,

Thanks :) If you are talking about audio receiver we can see in home app I think it is not possible since they are mainly airplay 2 device which is not really in HomeKit spec.

If you are talking about the icon itself of the TV device, I think it can be changed indeed but did not do so since most of use case are for tv .

In your case, you can merge on one accessory your switches I think using the individualAccessory option (set it to false )

**Comment by sleepyarmistice** [comment]
Yes, I was talking about the second situation. I was thinking it would be more than just a cosmetic change, though. Would this not enable volume controls for the receiver as well?

**Comment by nicoduj** [comment]
If current activity (input) on tv device controls sound of your receiver with volume up/ down, you will be able to set volume in remote control widget with physical buttons of your phone yes. But nothing to do with the icon itself which is purely cosmetic
