### ISSUE TITLE
An option to Trigger Switch flip while activity is starting or stopping

### ISSUE THREAD

**Issue by TheEngineerGuy** [nicoduj/homebridge-harmony#434]
**Is your feature request related to a problem? Please describe.**
Trigger Switch flip while activity is starting or stopping, vs once it has fully started or fully stopped.

**Describe the solution you'd like**
Not sure if Harmony provides status before the activity state has fully transitioned or not. But if it does provide information about an activity still in process of starting or stopping, then we could potentially add an option to reflect switch flip to happen when state change was initiated, vs when it was finished.

This would allow me to fast track some of the HomeKit automations to happen in parallel, rather than wait for them to start in series.

**Describe alternatives you've considered**
None that I can think of.

**Additional context**
Please do let me know if you would like additional info and I can provide it.

**Comment by nicoduj** [comment]
Hi, thanks for suggestion, however It seems a bit difficult to do at first. harmony does provide a state on activity transition, but the problem is more on homekit / homebridge side and the architecture of the plugin (which, to be honest, has become a bit "of a mess", since the beginning of this side project ad features added through time).  I feel that it would involves a lot of work and regression test to achieve, for a "niche" use case, and currently do not have time to do it.
