### ISSUE TITLE
use stateDigest to refresh instead of timer.

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#48]
use a websocket opened for getting state digest and update current activity instead of timer

**Comment by nicoduj** [comment]
done in 0.2.2

**Comment by Krocko** [comment]
I get the following error on every button press. 

`Feb 03 11:51:33 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:51:33 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:51:40 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:51:40 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:52:08 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:52:08 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:52:11 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:52:11 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:52:12 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:52:12 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:52:13 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:52:13 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:52:22 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:52:22 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:52:26 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:52:26 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:52:29 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:52:29 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:52:30 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:52:30 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:53:21 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:53:21 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:53:42 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:53:42 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:53:42 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:53:42 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:53:43 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: WebSocket closed with reason: connection failed (1006).
Feb 03 11:53:43 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:54:18 raspberrypi homebridge[13713]: [HarmonyHub] ERROR - setTimer wspRefresh :Error: Can't open WebSocket while closing.
Feb 03 11:54:18 raspberrypi homebridge[13713]: [HarmonyHub] INFO - relaunching timer
Feb 03 11:54:19 raspberrypi homebridge[13713]: /usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/dist/index.js:2
Feb 03 11:54:19 raspberrypi homebridge[13713]: !function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.WebSocketAsPromised=t():e.WebSocketAsPromised=t()}(this,function(){return function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}return n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t
Feb 03 11:54:19 raspberrypi homebridge[13713]: Error: Can't send data because WebSocket is not opened.
Feb 03 11:54:19 raspberrypi homebridge[13713]:     at t.throwIf (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/dist/index.js:2:43102)
Feb 03 11:54:19 raspberrypi homebridge[13713]:     at e.value (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/dist/index.js:2:13906)
Feb 03 11:54:19 raspberrypi homebridge[13713]:     at Timeout.timerID.setInterval [as _onTimeout] (/usr/local/lib/node_modules/homebridge-harmony/harmonyAsTVPlatform.js:146:54)
Feb 03 11:54:19 raspberrypi homebridge[13713]:     at listOnTimeout (timers.js:327:15)
Feb 03 11:54:19 raspberrypi homebridge[13713]:     at processTimers (timers.js:271:5)
`

**Comment by nicoduj** [comment]
I will check, anyone else have this issue ? Idon’t experience it myself

**Comment by nicoduj** [comment]
Ok I think I know what is happening. Will fix that asap

**Comment by Krocko** [comment]
Thank you very much for your fast updates. 
An other question. Is `addAllActivitiesToSkipedIfSameStateActivitiesList` and `showTurnOffActivity` supported in the `TVPlatformMode` or can i delete this lines in the config.json?

**Comment by nicoduj** [comment]
showTurnOffActivity Is not supported
addAllActivitiesToSkipedIfSameStateActivitiesList Is since 0.2.3

**Comment by nicoduj** [comment]
False.
These two are bind to return and home commands of your activity

**Comment by Krocko** [comment]
But this buttons don't work for me. 
Should i open an new issue?

**Comment by Krocko** [comment]
`Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Creating Main TV Service
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Creating InputSourceService Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Mute for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeDown for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeUp for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionDown for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionLeft for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionRight for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionUp for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Select for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Stop for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Play for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Rewind for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Pause for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping FastForward for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Return for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Menu for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Home for Filme
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Creating InputSourceService PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Mute for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeDown for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeUp for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionDown for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionLeft for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionRight for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionUp for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Select for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Stop for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Play for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Rewind for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Pause for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping FastForward for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping SkipBackward for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping SkipForward for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Return for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Menu for PlayStation 3 Slim
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Creating InputSourceService Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Mute for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeDown for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeUp for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionDown for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionLeft for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionRight for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionUp for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Select for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Stop for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Play for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Rewind for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Pause for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping FastForward for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Menu for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Home for Fernsehen Schlafzimmer
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Creating InputSourceService Musik Essbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeDown for Musik Essbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeUp for Musik Essbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Play for Musik Essbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Pause for Musik Essbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping SkipBackward for Musik Essbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping SkipForward for Musik Essbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Creating InputSourceService Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Mute for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeDown for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeUp for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionDown for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionLeft for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionRight for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionUp for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Select for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Stop for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Play for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Rewind for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Pause for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping FastForward for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping SkipBackward for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping SkipForward for Musik Wohnbereich
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Configuring Main Activity Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Creating TV Speaker Service
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Creating InputSourceService Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Mute for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeDown for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeUp for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionDown for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionLeft for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionRight for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionUp for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Select for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Stop for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Play for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Rewind for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Pause for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping FastForward for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Menu for Fern-sehen
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Creating InputSourceService Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Mute for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeDown for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping VolumeUp for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionDown for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionLeft for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionRight for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping DirectionUp for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Select for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Stop for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Play for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Rewind for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Pause for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping FastForward for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping SkipBackward for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping SkipForward for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Menu for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Return for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Mapping Home for Apple TV
Feb 05 14:36:18 raspberrypi homebridge[22163]: [HarmonyHub] Adding Accessory : HarmonyHub
`

**Comment by nicoduj** [comment]
Return seems to be mapped for filme, Apple TV and PlayStation 3 activity only.
Home for Fernsehen Schlafzimmer , filme, AppleTV
