### ISSUE TITLE
Inverse showTurnOffActivity

### ISSUE THREAD

**Issue by Krocko** [nicoduj/homebridge-harmony#86]
Is it possible to inverse the function of this button?
If nobody is at home and my "Leave home scene" fires, it looks better, if all devices are off. 
Now the home App shows one aktiv switch.

**Comment by nicoduj** [comment]
Hi, You can remove it from your state information list 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Krocko** [comment]
Yes, i know. But would be great to have this feature.

**Comment by nicoduj** [comment]
Ok, So you want this switch to be on  when something is on  and off when everything is off ? This way you will have to ask Siri to turn it off if you want to turn everything off , but turning it on will have no effect, that’s it ? Could make sense will think if it should be an option or not .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Krocko** [comment]
Yes exactly. 
Thank you very much.

**Comment by nicoduj** [comment]
If anybody else have an opinion about this , and especially if it should be a change or an option and what should be the default, speak now here or be quiet for ever :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DoctorExitus** [comment]
Maybe it is possible to make it a button instead of a switch. That way you could use it to switch everything off without permanently toggling it‘s state. The activity switches show their on/off state anyway, so a switch that shows the „off“ state of the activites by being „turned on“ is redundant info anyway.
However, I don‘t know if this is possible withing the limitations of homekit.

**Comment by nicoduj** [comment]
As far as I know there is no real button in HomeKit. This switch is already acting as a toggle switch when it is in its on state (it is returning to its state once activated).

However you are right we could set it as a toggle switch only but some relies on its on state for automations I think 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DoctorExitus** [comment]
Hmm okay, I suspected that HomeKit might not allow that. I don‘t really get why, because it supports physical toggle buttons, just not digital ones. Maybe Apple introduces more features with iOS 13. More conditions in the Homeapp would also be really useful.

Anyway, I don‘t have a use for this TurnOff switch, but I think the current logic is more intuitive. But I also get why Krocko finds it more aesthetically pleasing to have everything switched off. Maybe this can be solved by a second attribute (eg „-1“) that inverses the functionality (if possible). Or another function that is reversed by default so you can choose which to add in the config.
